name: recipe_reach
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3

  flutter:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.jpeg
    - assets/images/Chef.png
    - assets/images/Group.png
    - assets/images/Buy.png
    - assets/images/bg.png
    - assets/images/Image.png
